### ISSUE TITLE
Difference from ferrum?

### ISSUE THREAD

**Issue by rickychilcott** [Eth3rnit3/chromate#14]
I’m wondering what the difference is from [ferrum](https://github.com/rubycdp/ferrum). Would you be willing to document the purpose of this gem?

I’m looking forward to an agentic future in Ruby!

**Comment by Eth3rnit3** [comment]
While it's true that there are many similarities in approach, Ferrum doesn't aim to adopt human behavior; it's an extremely complete library for automating actions in headless chrome. But Ferrum's choice is to work with a notion of isolated context, which offers performance gains as well as other advantages. However, this practice implies the use of Chrome's incognito mode, which also has the effect of being practically stateless, or at least, of having sessions that last only as long as the context instance. This can have major advantages depending on the use case, but it also represents a constraint when you want to adopt human behavior, use chrome profiles, keep sessions, cookies... What's more, chromate natively provides behaviors such as the creation of a Béziers curve for mouse movements...

**Comment by rickychilcott** [comment]
That really helpful, thanks!

Ricky Chilcott

Co-founder

844-677-7526 x701

www.missionmet.com ( http://www.missionmet.com )

( https://www.missionmet.com/social/fb ) ( https://www.missionmet.com/social/tw ) ( http://www.missionmet.com/social/yt ) ( https://www.missionmet.com/social/ln )

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
